---
all:
  vars:
    param_resourcegroup: GuacamoleTest
    param_source_address_prefix: "160.86.236.182"
    param_default_instance_type: Standard_D2s_v3
    param_default_disk_type: Standard_LRS
    param_default_username: procube
    param_location: JapanEast
    param_subscription_id: 3c45baae-d3b1-4b65-98c8-e77738697647
    param_default_azure_image:
      offer: windows-11
      publisher: MicrosoftWindowsDesktop
      sku: 'win11-22h2-pro'
      version: latest
    param_default_password: "{{ lookup('password', '.password length=15 chars=ascii_letters,digits') }}"
  children:
    guacamoles:
      hosts:
        guacamole:
          hive_safe_admin: guacamole
          hive_home_dir: "/home/{{ hive_safe_admin }}"
    jumpservers:
      hosts:
        js-test:
          username: mitsuru
        #fdma-test-1:
        #username: ishida
        # dc:
        #   username: procube
        #   vm_image:
            # offer: WindowsServer
            # publisher: MicrosoftWindowsServer
            # # sku: '2012-Datacenter'
            # # sku: '2016-Datacenter'
            # sku: '2019-Datacenter'
            # # sku: '2022-Datacenter'
            # version: latest

            # offer: windows-10
            # publisher: MicrosoftWindowsDesktop
            # sku: 'win10-21h2-pro'
            # version: latest
            
            # offer: visualstudio2022
            # publisher: microsoftvisualstudio
            # sku: 'vs-2022-ent-latest-ws2022'
